# Generated by Django 5.2 on 2025-04-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parentname', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Studentname', models.CharField(max_length=20)),
                ('Message', models.CharField(max_length=20)),
            ],
        ),
    ]
